### ISSUE TITLE
double-float postfix "d0" is not recognized

### ISSUE THREAD

**Issue by ghost** [dylan-lang/atom-language-dylan#2]
the `<double-float>`\- postfix 1.0**d0** is not recognized.  the following regex should fix it:

```
'\\b((#x[0-9a-fA-F]*)|(([0-9]+\\.?[0-9]*)|(\\.[0-9]+))(((e|E)(\\+|-)?[0-9]+)?|(d0)?))\\b'
```

as far as i can see it, are literals like `1.0e-2d0` not allowed.

**Comment by housel** [comment]
The d0 is itself an exponent. The corresponding double float literal would be 1.0d-2. The regex should match [eEsSdDxX] at the beginning of the exponent portion.
